ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax_amount NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK(tax_amount>=0);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS tax_provider TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS fx_rate NUMERIC(20,10);
ALTER TABLE orders ADD COLUMN IF NOT EXISTS fx_provider TEXT;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS pricing_snapshot JSONB NOT NULL DEFAULT '{}';
CREATE INDEX IF NOT EXISTS orders_currency_idx ON orders(currency,created_at DESC);
